// Danh sách các phường TP.HCM (theo địa chỉ mới sau sắp xếp 2025)
export const HCM_WARDS = [
  // Quận 1
  'Phường Sài Gòn',
  'Phường Tân Định',
  'Phường Bến Thành',
  'Phường Đa Kao',
  'Phường Cầu Ông Lãnh',
  'Phường Cô Giang',
  'Phường Cầu Kho',
  'Phường Nguyễn Cư Trinh',
  'Phường Đa Kao',
  
  // Quận 2
  'Phường An Phú',
  'Phường An Khánh',
  'Phường Bình An',
  'Phường Bình Khánh',
  'Phường Bình Trưng Đông',
  'Phường Bình Trưng Tây',
  'Phường Cát Lái',
  'Phường Thạnh Mỹ Lợi',
  'Phường Thảo Điền',
  'Phường Thủ Thiêm',
  
  // Quận 3
  'Phường Võ Thị Sáu',
  'Phường Đa Kao',
  'Phường Bàn Cờ',
  'Phường Xuân Hòa',
  'Phường Nhiêu Lộc',
  'Phường Cầu Ông Lãnh',
  'Phường Cô Giang',
  'Phường Nguyễn Cư Trinh',
  'Phường Cầu Kho',
  'Phường Thạnh Xuân',
  'Phường Thạnh Lộc',
  'Phường Hiệp Thành',
  'Phường Thới An',
  'Phường Tân Chánh Hiệp',
  'Phường An Phú Đông',
  'Phường Tân Thới Hiệp',
  'Phường Trung Mỹ Tây',
  'Phường Tân Hưng Thuận',
  'Phường Đông Hưng Thuận',
  'Phường Tân Thới Nhất',
  
  // Quận 4
  'Phường Vĩnh Hội',
  'Phường Khánh Hội',
  'Phường Xóm Chiếu',
  'Phường Cầu Kho',
  'Phường Cầu Ông Lãnh',
  'Phường Nguyễn Thái Bình',
  'Phường Đa Kao',
  'Phường Tân Định',
  
  // Quận 5
  'Phường Phạm Ngũ Lão',
  'Phường Cầu Ông Lãnh',
  'Phường Cô Giang',
  'Phường Nguyễn Cư Trinh',
  'Phường Cầu Kho',
  'Phường Đa Kao',
  'Phường Tân Định',
  
  // Quận 6
  'Phường 1',
  'Phường 2',
  'Phường 3',
  'Phường 4',
  'Phường 5',
  'Phường 6',
  'Phường 7',
  'Phường 8',
  'Phường 9',
  'Phường 10',
  'Phường 11',
  'Phường 12',
  'Phường 13',
  'Phường 14',
  
  // Quận 7
  'Phường Tân Phú',
  'Phường Tân Phong',
  'Phường Tân Quy',
  'Phường Tân Thuận Đông',
  'Phường Tân Thuận Tây',
  'Phường Bình Thuận',
  'Phường Phú Mỹ',
  'Phường Phú Thuận',
  'Phường Tân Hưng',
  'Phường Tân Kiểng',
  'Phường Tân Phong',
  'Phường Tân Quy Đông',
  'Phường Tân Quy Tây',
  'Phường Tân Thuận Đông',
  'Phường Tân Thuận Tây',
  
  // Quận 8
  'Phường 1',
  'Phường 2',
  'Phường 3',
  'Phường 4',
  'Phường 5',
  'Phường 6',
  'Phường 7',
  'Phường 8',
  'Phường 9',
  'Phường 10',
  'Phường 11',
  'Phường 12',
  'Phường 13',
  'Phường 14',
  'Phường 15',
  'Phường 16',
  
  // Quận 9
  'Phường Hiệp Phú',
  'Phường Long Bình',
  'Phường Long Phước',
  'Phường Long Thạnh Mỹ',
  'Phường Long Trường',
  'Phường Phú Hữu',
  'Phường Phước Long A',
  'Phường Phước Long B',
  'Phường Tân Phú',
  'Phường Tăng Nhơn Phú A',
  'Phường Tăng Nhơn Phú B',
  'Phường Trường Thạnh',
  
  // Quận 10
  'Phường 1',
  'Phường 2',
  'Phường 3',
  'Phường 4',
  'Phường 5',
  'Phường 6',
  'Phường 7',
  'Phường 8',
  'Phường 9',
  'Phường 10',
  'Phường 11',
  'Phường 12',
  'Phường 13',
  'Phường 14',
  'Phường 15',
  
  // Quận 11
  'Phường Minh Phụng',
  'Phường Bình Thới',
  'Phường Hòa Bình',
  'Phường Phú Thọ',
  'Phường 1',
  'Phường 2',
  'Phường 3',
  'Phường 4',
  'Phường 5',
  'Phường 6',
  'Phường 7',
  'Phường 8',
  'Phường 9',
  'Phường 10',
  'Phường 11',
  'Phường 12',
  'Phường 13',
  'Phường 14',
  'Phường 15',
  'Phường 16',
  
  // Quận 12
  'Phường An Phú Đông',
  'Phường Đông Hưng Thuận',
  'Phường Hiệp Thành',
  'Phường Tân Chánh Hiệp',
  'Phường Tân Hưng Thuận',
  'Phường Tân Thới Hiệp',
  'Phường Tân Thới Nhất',
  'Phường Thạnh Lộc',
  'Phường Thạnh Xuân',
  'Phường Thới An',
  'Phường Trung Mỹ Tây',
  
  // Quận Bình Thạnh
  'Phường 1',
  'Phường 2',
  'Phường 3',
  'Phường 4',
  'Phường 5',
  'Phường 6',
  'Phường 7',
  'Phường 8',
  'Phường 9',
  'Phường 10',
  'Phường 11',
  'Phường 12',
  'Phường 13',
  'Phường 14',
  'Phường 15',
  'Phường 16',
  'Phường 17',
  'Phường 18',
  'Phường 19',
  'Phường 20',
  'Phường 21',
  'Phường 22',
  'Phường 23',
  'Phường 24',
  'Phường 25',
  'Phường 26',
  'Phường 27',
  'Phường 28',
  
  // Quận Tân Bình
  'Phường 1',
  'Phường 2',
  'Phường 3',
  'Phường 4',
  'Phường 5',
  'Phường 6',
  'Phường 7',
  'Phường 8',
  'Phường 9',
  'Phường 10',
  'Phường 11',
  'Phường 12',
  'Phường 13',
  'Phường 14',
  'Phường 15',
  
  // Quận Tân Phú
  'Phường Hiệp Tân',
  'Phường Hòa Thạnh',
  'Phường Phú Thạnh',
  'Phường Phú Thọ Hòa',
  'Phường Phú Trung',
  'Phường Sơn Kỳ',
  'Phường Tân Quý',
  'Phường Tân Sơn Nhì',
  'Phường Tân Thành',
  'Phường Tân Thới Hòa',
  'Phường Tây Thạnh',
  
  // Quận Phú Nhuận
  'Phường 1',
  'Phường 2',
  'Phường 3',
  'Phường 4',
  'Phường 5',
  'Phường 6',
  'Phường 7',
  'Phường 8',
  'Phường 9',
  'Phường 10',
  'Phường 11',
  'Phường 12',
  'Phường 13',
  'Phường 14',
  'Phường 15',
  
  // Quận Gò Vấp
  'Phường 1',
  'Phường 2',
  'Phường 3',
  'Phường 4',
  'Phường 5',
  'Phường 6',
  'Phường 7',
  'Phường 8',
  'Phường 9',
  'Phường 10',
  'Phường 11',
  'Phường 12',
  'Phường 13',
  'Phường 14',
  'Phường 15',
  'Phường 16',
  'Phường 17',
  
  // Quận Bình Tân
  'Phường An Lạc',
  'Phường An Lạc A',
  'Phường Bình Hưng Hòa',
  'Phường Bình Hưng Hòa A',
  'Phường Bình Hưng Hòa B',
  'Phường Bình Trị Đông',
  'Phường Bình Trị Đông A',
  'Phường Bình Trị Đông B',
  'Phường Tân Tạo',
  'Phường Tân Tạo A',
  
  // Quận Thủ Đức
  'Phường An Khánh',
  'Phường An Phú',
  'Phường Bình An',
  'Phường Bình Chiểu',
  'Phường Bình Thọ',
  'Phường Bình Trưng Đông',
  'Phường Bình Trưng Tây',
  'Phường Cát Lái',
  'Phường Hiệp Bình Chánh',
  'Phường Hiệp Bình Phước',
  'Phường Linh Chiểu',
  'Phường Linh Đông',
  'Phường Linh Tây',
  'Phường Linh Trung',
  'Phường Linh Xuân',
  'Phường Long Bình',
  'Phường Long Phước',
  'Phường Long Thạnh Mỹ',
  'Phường Long Trường',
  'Phường Phú Hữu',
  'Phường Phước Long A',
  'Phường Phước Long B',
  'Phường Tam Bình',
  'Phường Tam Phú',
  'Phường Tân Phú',
  'Phường Tăng Nhơn Phú A',
  'Phường Tăng Nhơn Phú B',
  'Phường Thảo Điền',
  'Phường Thạnh Mỹ Lợi',
  'Phường Thủ Thiêm',
  'Phường Trường Thạnh',
  
  // Huyện Bình Chánh
  'Xã An Phú Tây',
  'Xã Bình Chánh',
  'Xã Bình Hưng',
  'Xã Bình Lợi',
  'Xã Đa Phước',
  'Xã Hưng Long',
  'Xã Lê Minh Xuân',
  'Xã Phạm Văn Hai',
  'Xã Phong Phú',
  'Xã Quy Đức',
  'Xã Tân Kiên',
  'Xã Tân Nhựt',
  'Xã Tân Quý Tây',
  'Xã Tân Túc',
  'Xã Vĩnh Lộc A',
  'Xã Vĩnh Lộc B',
  
  // Huyện Cần Giờ
  'Xã An Thới Đông',
  'Xã Bình Khánh',
  'Xã Cần Thạnh',
  'Xã Long Hòa',
  'Xã Lý Nhơn',
  'Xã Tam Thôn Hiệp',
  'Xã Thạnh An',
  
  // Huyện Củ Chi
  'Xã An Nhơn Tây',
  'Xã An Phú',
  'Xã Bình Mỹ',
  'Xã Củ Chi',
  'Xã Hòa Phú',
  'Xã Nhuận Đức',
  'Xã Phạm Văn Cội',
  'Xã Phú Hòa Đông',
  'Xã Phú Mỹ Hưng',
  'Xã Phước Hiệp',
  'Xã Phước Thạnh',
  'Xã Phước Vĩnh An',
  'Xã Tân An Hội',
  'Xã Tân Phú Trung',
  'Xã Tân Thạnh Đông',
  'Xã Tân Thạnh Tây',
  'Xã Tân Thông Hội',
  'Xã Thái Mỹ',
  'Xã Trung An',
  'Xã Trung Lập Hạ',
  'Xã Trung Lập Thượng',
  
  // Huyện Hóc Môn
  'Xã Bà Điểm',
  'Xã Đông Thạnh',
  'Xã Nhị Bình',
  'Xã Tân Hiệp',
  'Xã Tân Thới Nhì',
  'Xã Tân Xuân',
  'Xã Thới Tam Thôn',
  'Xã Trung Chánh',
  'Xã Xuân Thới Đông',
  'Xã Xuân Thới Sơn',
  'Xã Xuân Thới Thượng',
  
  // Huyện Nhà Bè
  'Xã Hiệp Phước',
  'Xã Long Thới',
  'Xã Nhà Bè',
  'Xã Nhơn Đức',
  'Xã Phú Xuân',
  'Xã Phước Kiển',
  'Xã Phước Lộc',
  
  // Huyện Củ Chi (tiếp)
  'Thị trấn Củ Chi',
].sort();
